api/urls.py
from django.urls import path

from api.views import bbs, BbDetailView, comments

urlpatterns = [
    path('bbs/<int:pk>/comments', comments),
    path('bbs/<int:pk>', BbDetailView.as_view()),
    path('bbs/', bbs),
]

bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, BBPasswordChangeView, \
    RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail, profile_bb_detail, \
    profile_bb_add, profile_bb_change, profile_bb_delete

app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from main.apps import user_registered
from .models import AdvUser, SuperRubric, SubRubric, Bb, AdditionalImage, Comment
from captcha.fields import CaptchaField


class ChangeUserInfoForm(forms.ModelForm):
    """Форма для зміни особистих даних"""

    email = forms.EmailField(required=True, label="Адреса електронної пошти")

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_massage')


class RegisterUserForm(forms.ModelForm):
    """Форма для занесення інформації щодо нового користувача"""

    email = forms.EmailField(required=True, label='Адреса електронної пошти')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль(повторіть)', widget=forms.PasswordInput,
                                help_text='Введить будь ласка ще раз пароль для перевірки')

    def clean_password1(self):
        """Форма для валідації паролю"""

        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        """Форма для перевірка на співпадіння паролів"""

        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password1']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введені паролі не співпадають', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        """Форма для зберігання нового користувача та відправлення користувачу листа (user_registered)"""

        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_massage')


class SubRubricForm(forms.ModelForm):
    """Форма для занесення назви надрубрик"""
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None, label='Надрубрика',
                                          required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class SearchForm(forms.Form):
    """Форма для здійснення пошуку за введеним словом"""
    keywords = forms.CharField(required=False, max_length=20, label='')


class BbForm(forms.ModelForm):
    """Форма для введення користувачем оголошення"""
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


class UserCommentForm(forms.ModelForm):
    """Форма для коментування оголошення зареєстрованим користувачем"""

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    """Форма для коментування оголошення не зареєстрованим користувачем"""

    captcha = CaptchaField(label='Введіть текст з картинки', error_messages={'invalid': 'Невірний текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

main/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.core.signing import BadSignature
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView

from .forms import ChangeUserInfoForm, RegisterUserForm, SearchForm, BbForm, AIFormSet, UserCommentForm, \
    GuestCommentForm
from .models import AdvUser, SubRubric, Bb, Comment
from .utilities import signer


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)


def other_page(request, page):
    """Контролер - функція для відображення додаткових сторінок"""

    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


class BBLoginView(LoginView):
    """Контролер - клас для виконання входу"""

    template_name = 'main/login.html'


@login_required
def profile(request):
    """Контролер функція для відображення профілю користувача та його оголошень"""
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


class BBLogoutView(LoginRequiredMixin, LogoutView):
    """Контролер клас для виконання виходу"""

    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Контролер клас для зміни особистих даних користувача"""

    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Дані користувача змінено'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    """Контролер клас для зміни пароля користувача"""
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль користувача змінено'


class RegisterUserView(CreateView):
    """Контролер клас для реєстрації користувача"""

    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    """Контролер класс для відображення інформації про успішну реестрацію"""
    template_name = 'main/register_done.html'


def user_activate(request, sign):
    """Контролер функція для активації користувача через e-mail"""

    try:
        user_name = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, user_name=user_name)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    """Контролер клас для видалення користувачів"""

    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Користувача видалено')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def by_rubric(request, pk):
    """Контролер функція для пошуку за введеним словом"""

    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list, 'form': form}
    return render(request, 'main/by_rubric.html', context)


def detail(request, rubric_pk, pk):
    """Контролер функція для відображення обраного товару"""

    bb = Bb.objects.get(pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {'bb': bb.pk}
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Коментарій додано')
        else:
            form = c_form
            messages.add_message(request, messages.SUCCESS, 'Коментарій не додано')
    context = {'bb': bb, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/detail.html', context)


@login_required
def profile_bb_detail(request, pk):
    """Контролер функція для відображення обраного власного товару зареєстрованим користувачем """

    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/profile_bb_detail.html', context)


@login_required
def profile_bb_add(request):
    """Контролер функція для додавання оголошення зареєстрованим користувачем """

    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Оголошення додано')
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_add.html', context)


@login_required
def profile_bb_change(request, pk):
    """Контролер функція для внесення змін до оголошення зареєстрованим користувачем """
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILE, instance=bb)
        if form.is_valid:
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILE, instance=bb)
            if formset.ia_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Оголошення збережено')
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    contex = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_change.html', contex)


@login_required
def profile_bb_delete(request, pk):
    """Контролер функція для видалення оголошення зареєстрованим користувачем """
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, 'Оголошення видалено')
        return redirect('main:profile')
    else:
        context = {'bb': bb}
        return render(request, 'main/profile_bb_delete.html', context)

templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %} Про сайт {% endblock %}

{% block content %}
<h2>Про сайт</h2>
<p>Сайт розроблено для публікації оголошень шодо продажу, з поділом на рубрики та підрубрики</p>
{% endblock %}

templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %} Ошибка при активайції {% endblock %}

{% block content %}
<h2>Активація</h2>
<p>Активація не пройшла </p>
<p><a href="{% url 'main:register' %}">Зарееструватись ще раз</a></p>
{% endblock %}

templates/main/by_rubric.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Шукати' button_type='submit' %}
        </form>
    </div>
</div>
{% if bbs %}
<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.png' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">
                {{ bb.title }}</a></h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} грн.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Правка особистих даних {% endblock %}

{% block content %}
<h2>Правка особистих даних користувача {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зберігти' %} {% endbuttons %}
</form>
{% endblock %}

templates/main/index.html
{% extends "layout/basic.html" %}

{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>

<ul class="list-unstyled">
    {% for bb in bbs %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <a href="{{ url }}{{ all }}">
            {% if bb.image %}
            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
            {% else %}
            <img class="mr-3" src="{% static 'main/empty.png' %}">
            {% endif %}
        </a>
        <div class="media-body">
            <h3><a href="{{ url }}{{ all }}">
                {{ bb.title }}</a></h3>
            <div>{{ bb.content }}</div>
            <p class="text-right font-weight-bold">{{ bb.price }} грн.</p>
            <p class="text-right font-italic">{{ bb.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/main/login.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %} Вхід {% endblock %}

{% block content %}
<h2>Вхід</h2>
{% if user.is_authenticated %}
<p>Ви вже здійснили вхід.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Увійти' %} {% endbuttons %}
</form>
{% endif %}
{% endblock %}

templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %} Вихід {% endblock %}

{% block content %}
<h2>Ви успішно вийшли з сайту</h2>
{% endblock %}

templates/main/password_change.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %} Зміна пароля користувача {% endblock %}

{% block content %}
<h2>Зміна пароля користувача</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Змінити пароль' %}{% endbuttons %}
</form>
{% endblock %}

templates/main/profile_bb_add.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %} Додавання оголошення - Профіль користувача {% endblock %}
{% block content %}
<h2>Додавання оголошення</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% buttons submit='Додати' %} {% endbuttons %}
</form>
{% endblock %}

templates/main/profile_bb_delete.html
{% extends 'layout/basic.html' %}

{% load bootstrap4 %}

{% block title %} Видалення оголошення - Профіль користувача {% endblock %}
{% block content %}
<h2>Видалення оголошення</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% buttons submit='Видалити' %} {% endbuttons %}
</form>
{% endblock %}

templates/main/profile_bb_detail.html
{% extends 'layout/basic.html' %}

{% block title %} {{ bb.title }} - {{ bb.rubric.name }} {% endblock %}

{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        {% if bb.image %}
        <div class="col-md-auto"><img src="{{ bb.image.url }}" class="main-image" alt="Зображення відсутне">
        </div>
        {% endif %}
        <div class="col">
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p class="font-weight-bold">{{ bb.price }} грн.</p>
            <p>{{ bb.contacts }}</p>
            <p class="text-right font-italic">Додано {{ bb.created_at }}</p>
        </div>
    </div>
</div>
{% if ais %}
<div class="'d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div>
        <img class="additional-image" src="{{ ai.image.url }}" alt="Зображення відсутне">
    </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}"> Повернутись></a></p>
{% endblock %}

templates/main/register_done.html
{% extends "layout/basic.html" %}


{% block title %} Реестрація завершена{% endblock %}

{% block content %}
<h2>Реестрація</h2>
<p>реестрація користувача завершена</p>
<p>На адресу вказаної електронної пошти напралено відповідний лист для активації користувача</p>
{% endblock %}

templates/main/register_user.html
{%  extends 'layout/basic.html'%}

{% load bootstrap4 %}

{% block title %} Реєстрація {% endblock %}

{% block content %}
<h2>Реєстрація нового користувача</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Зареєструватись' %} {% endbuttons %}
</form>
{% endblock %}

templates/main/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %} Користувач вже активований {% endblock %}

{% block content %}
<h2>Активація</h2>
<p>Користувач з таким ім'ям вже активовано раніше</p>
<p><a href="{% url 'main:login' %}">Увійти на сайт</a></p>
{% endblock %}