api/urls.py
from django.urls import path

from api.views import bbs, BbDetailView, comments

urlpatterns = [
    path('bbs/<int:pk>/comments', comments),
    path('bbs/<int:pk>', BbDetailView.as_view()),
    path('bbs/', bbs),
]

bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView, BBPasswordChangeView, \
    RegisterUserView, RegisterDoneView, user_activate, DeleteUserView, by_rubric, detail, profile_bb_detail, \
    profile_bb_add, profile_bb_change, profile_bb_delete

app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

templates/layout/basic.html
{% load bootstrap4 %}
{%load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title> {% block title%} Головна {% endblock %} Дошка - оголошень </title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="container-fluid">
        <header class="mb-4">
            <h1 class="display-1 text-center">Сайт оголошень</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item"><a class="nav-link" href = "{% url 'main:register' %}"> Реєстрація </a></li>
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="true" aria-expanded="false">Профіль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Moї оголошення</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change' %}">Змінити особисті данні</a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Змінити пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Вийти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:profile_delete' %}">Видалити</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:login' %}">Вхід</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root"
                href="{% url 'main:index' %}">Головна</a>
                    {% for rubric in rubrics %}
                {% ifchanged rubric.super_rubric.pk %}
                <span class="nav-link root font-weight-bold">
                    {{ rubric.super_rubric.name }}</span>
                {% endifchanged %}
            <a class="nav-link" href="{% url 'main:by_rubric' pk=rubric.pk %}">{{ rubric.name }}</a>
            {% endfor %}
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">Про сайт</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; Konstantin Kononenko</p>
        </footer>
    </body>
</html>